title: Lyn's Blog
description: Bioinformatics | Single-cell Genomics | AI-driven Research
baseurl: /git_blog
url: "https://lynhsiong.github.io"
permalink: pretty
# Jekyll 3.x default theme (overridden by _layouts/default.html)
theme: minima
